#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5

cd "$(git rev-parse --show-toplevel)"

banner "Cloudflare account + first deploy"

# ── 1. Client owns the account (ADR-0005) ────────────────────────────────
stage "Client: create the Cloudflare account"
say "Cloudflare forbids signing up on behalf of a third party. The client creates this account. You do not."
open_url "https://dash.cloudflare.com/sign-up"
step "Hand the keyboard to the client (or sit with them)."
step "Email: use a company address they control, not yours. A shared alias like cloudflare@their-domain is ideal."
step "Enter email + password, then Create Account."
step "Open the verification email Cloudflare sends and confirm the address."
note "If the dashboard asks to add a website, skip it. This project deploys a Worker, not a proxied domain."
pause "Press Enter when the client is signed in with a verified email."

# ── 2. Developer is a member ─────────────────────────────────────────────
stage "Client: invite you as Administrator"
say "The client stays Super Administrator (billing + members). You get Administrator: full account except members and billing profile."
open_url "https://dash.cloudflare.com/?to=/:account/members"
step "Still as the client: Members → Invite."
step "Invite members: paste your email (the developer)."
step "Scope: leave at the whole account."
step "Roles: Administrator. Do not pick Super Administrator."
step "Continue to summary → Invite."
step "You (developer): open the invite email, accept, and sign in."
pause "Press Enter when you can open this Cloudflare account as yourself."

# ── 3. Account ID ────────────────────────────────────────────────────────
stage "Copy the account ID"
say "CI needs CLOUDFLARE_ACCOUNT_ID. It is an ID, not a password — still stored as a GitHub secret because that is what the workflow reads."
open_url "https://dash.cloudflare.com/?to=/:account/workers-and-pages"
step "On Workers & Pages, find Account Details."
step "Click the copy button next to Account ID."
note "Or press CMD/CTRL+K anywhere in the dashboard, type Copy account ID, and select it."
ask CLOUDFLARE_ACCOUNT_ID "Paste the account ID:"
write_env CLOUDFLARE_ACCOUNT_ID "$CLOUDFLARE_ACCOUNT_ID"
set_secret CLOUDFLARE_ACCOUNT_ID "$CLOUDFLARE_ACCOUNT_ID"

# ── 4. API token ─────────────────────────────────────────────────────────
stage "Create a Workers deploy token"
say "This token can deploy Workers on the client's account. Shown once. Never commit it."
open_url "https://dash.cloudflare.com/?to=/:account/api-tokens"
step "Select Create Token."
step "Under Permission policies, open the Custom dropdown and choose Edit Cloudflare Workers."
step "Name it something like 'GitHub Actions deploy'."
step "Account resources: include only this one account, not all accounts."
step "Continue to summary → Create Token."
step "Copy the token immediately. You will not see it again."
note "If Account API tokens is missing, use My Profile → API Tokens (https://dash.cloudflare.com/profile/api-tokens) → Create Token → Edit Cloudflare Workers template, scoped to this account."
ask_secret CLOUDFLARE_API_TOKEN "Paste the API token:"
write_env CLOUDFLARE_API_TOKEN "$CLOUDFLARE_API_TOKEN"
set_secret CLOUDFLARE_API_TOKEN "$CLOUDFLARE_API_TOKEN"

# ── 5. First CI deploy ───────────────────────────────────────────────────
stage "Dispatch the first CI deploy"
say "Deploy comes from GitHub Actions, not wrangler on your laptop. GitHub only lists workflow_dispatch for workflows that exist on the default branch (main). This app's workflow currently lives on sheet-variant, so dispatch may be refused until that file is on main."
_branch="$(git branch --show-current)"
if confirm "Try to dispatch workflow CI on ${_branch}?"; then
  if gh workflow run CI --ref "$_branch"; then
    say "Dispatched. The deploy job needs the two secrets you just set."
  else
    warn "Dispatch failed. Usual cause: CI.yml is not on main. Secrets are still set; the Worker appears after this workflow exists on the default branch, or after a push to main."
  fi
fi
open_url "https://github.com/anmolg27/holidays-website/actions"
step "Actions → CI → the latest run. Test job does not need secrets; Deploy does."
open_url "https://dash.cloudflare.com/?to=/:account/workers-and-pages"
step "When the Worker exists, open uttarakhand-tours-website and copy its workers.dev URL."
note "First Worker on an account: Cloudflare may ask you to pick a *.workers.dev subdomain. Do that, then come back."
if confirm "Is the placeholder page live at a workers.dev URL?"; then
  ask WORKERS_DEV_URL "Paste the public URL:"
  write_env WORKERS_DEV_URL "$WORKERS_DEV_URL"
fi

finish
